Repository 2025-HELLO/HELLO-ADMIN, pull requests merged in 2025-08, with the labels that each got.

#2 Init: 프로젝트 초기 세팅
  .coderabbit.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  .prettierrc
  .svgrrc.json
  eslint.config.js
  eslint.config.ts
  index.html
  package.json
  pnpm-lock.yaml
  public/svgs/ic_back.svg
  public/svgs/ic_profile.svg
  src/App.tsx
  src/apis/axiosIntance.ts
  src/apis/constants/.gitkeep
  src/apis/constants/endPoint.ts
  src/apis/constants/httpState.ts
  src/assets/images/.gitkeep
  src/assets/images/logo.png
  src/assets/svgs/.gitkeep
  src/assets/svgs/IcBack.tsx
  src/assets/svgs/IcProfile.tsx
  src/assets/svgs/index.ts
  src/common/components/.gitkeep
  src/common/components/header/Header.css.ts
  src/common/components/header/Header.tsx
  src/common/components/header/PageHeader.css.ts
  src/common/components/header/PageHeader.tsx
  src/common/utils/.gitkeep
  src/common/utils/queryClient.ts
  src/main.tsx
  src/pages/home/page/Home.css.ts
  src/pages/home/page/Home.tsx
  src/shared/components/.gitkeep
  src/shared/components/layout/Layout.tsx
  src/shared/constants/path.ts
  src/shared/routes/.gitkeep
  src/shared/routes/MainRoutes.tsx
  src/shared/routes/router.tsx
  src/shared/styles/global.css.ts
  src/shared/styles/reset.css.ts
  src/shared/styles/token/.gitkeep
  src/shared/styles/token/color.css.ts
  src/shared/styles/token/index.ts
  src/shared/styles/token/layout.css.ts
  src/shared/styles/token/typography.css.ts
  src/shared/styles/token/zIndex.css.ts
  tsconfig.app.json
  vite.config.ts
Labels: ⚙️ Setting, 🐵 지수

#7 Feat: 홈화면 UI구현
  public/svgs/ic_home_chat.svg
  public/svgs/ic_home_rec.svg
  src/pages/home/page/Home.css.ts
  src/pages/home/page/Home.tsx
Labels: ✨ Feature, 😺 서연

#9 Feat: 챗봇 카톡 데이터 수집 UI 구현
  public/svgs/ic_cacao.svg
  public/svgs/ic_information.svg
  public/svgs/ic_protection.svg
  public/svgs/ic_uproad.svg
  src/pages/data/chat/page/ChatCollector.css.ts
  src/pages/data/chat/page/ChatCollector.tsx
  src/pages/home/page/Home.tsx
  src/shared/constants/path.ts
  src/shared/routes/MainRoutes.tsx
Labels: ✨ Feature, 😺 서연

#12 Feat: 주간보고서 퍼블리싱
  public/svgs/ic_uparrow.svg
  src/assets/svgs/IcRightarrow.tsx
  src/assets/svgs/IcUparrow.tsx
  src/assets/svgs/index.ts
  src/pages/data/chat/page/ChatCollector.tsx
  src/pages/home/page/Home.tsx
  src/pages/weekly-report/components/GameReport.tsx
  src/pages/weekly-report/components/MealDonut.tsx
  src/pages/weekly-report/components/MealPatternReport.tsx
  src/pages/weekly-report/components/MedicationReport.tsx
  src/pages/weekly-report/components/ReminiscenceReport.tsx
  src/pages/weekly-report/components/ScheduleReport.tsx
  src/pages/weekly-report/components/WakeTimeReport.tsx
  src/pages/weekly-report/components/index.ts
  src/pages/weekly-report/constants/days.ts
  src/pages/weekly-report/mocks/reportData.ts
  src/pages/weekly-report/page/WeeklyReportDetail.css.ts
  src/pages/weekly-report/page/WeeklyReportDetail.tsx
Labels: ✨ Feature, 🐵 지수

#15 Feat: 관리자 회원가입 뷰 구현
  eslint.config.ts
  package.json
  pnpm-lock.yaml
  public/svgs/ic_copy.svg
  public/svgs/ic_notification.svg
  src/assets/svgs/IcCopy.tsx
  src/assets/svgs/IcNotification.tsx
  src/assets/svgs/index.ts
  src/common/components/progress/ProgressBar.css.ts
  src/common/components/progress/ProgressBar.tsx
  src/pages/signup/components/StepLayout.tsx
  src/pages/signup/components/step/AccountStep.tsx
  src/pages/signup/components/step/DoneStep.tsx
  src/pages/signup/components/step/NotifyStep.tsx
  src/pages/signup/components/step/ParentInfoStep.tsx
  src/pages/signup/components/step/TermsStep.tsx
  src/pages/signup/components/sub/AddMoreBox.tsx
  src/pages/signup/components/sub/DoseSelector.tsx
  src/pages/signup/components/sub/DrugFields.tsx
  src/pages/signup/components/sub/ParentBasicFields.tsx
  src/pages/signup/components/sub/ParentSummaryList.tsx
  src/pages/signup/components/sub/TimeBlock.tsx
  src/pages/signup/components/sub/index.ts
  src/pages/signup/constants/medication.ts
  src/pages/signup/hooks/useParentForm.ts
  src/pages/signup/page/Signup.css.ts
  src/pages/signup/page/Signup.tsx
  src/pages/signup/types.ts
  src/pages/signup/utils/parent.ts
  src/shared/constants/times.ts
  src/shared/routes/MainRoutes.tsx
  src/shared/styles/token/layout.css.ts
Labels: ✨ Feature, 🐵 지수
